#!/bin/bash

echo "🚀 Quick Deployment for aroundmenowapp.com"
echo ""

echo "📋 What you need to do:"
echo ""
echo "1. 🎯 DEPLOY FRONTEND (Vercel):"
echo "   Run: vercel --prod"
echo "   Then: vercel domains add aroundmenowapp.com"
echo ""
echo "2. 🎯 DEPLOY BACKEND (Railway):"
echo "   - Go to https://railway.app"
echo "   - Sign up with GitHub"
echo "   - Create new project"
echo "   - Connect your GitHub repo"
echo "   - Set environment variables"
echo ""
echo "3. 🎯 SET UP DATABASE:"
echo "   - Create PostgreSQL database"
echo "   - Add DATABASE_URL to Railway"
echo ""
echo "4. 🎯 CONFIGURE DNS:"
echo "   - Point aroundmenowapp.com to Vercel"
echo "   - Point api.aroundmenowapp.com to Railway"
echo ""
echo "5. 🎯 TEST EVERYTHING:"
echo "   - Test https://aroundmenowapp.com"
echo "   - Test https://api.aroundmenowapp.com/health"
echo ""

echo "✅ Your app is ready for deployment!"
echo "📖 See QUICK_DEPLOYMENT_GUIDE.md for detailed steps"
echo ""
echo "🚀 Ready to launch aroundmenowapp.com!" 